### ISSUE TITLE
JSPerf

### ISSUE THREAD

**Issue by Cristy94** [mreinstein/remove-array-items#6]
I have created a JSPerf for testing `remove-array-items` vs `splice`.

https://jsperf.com/slice-vs-remove-array-items/1

For small arrays (<10.000 elements) remove-array-items is faster, for large arrays it (100k of elements) it can become pretty slow.

Thought you might want to add some benchmarks to the WIKI/Readme.

**Comment by mreinstein** [comment]
Thanks, I appreciate the effort. 

The primary raison d'être of this module is _to avoid generation of garbage when removing array items_ . For most javascript usage (web page scripts or backend route handlers) this is not a concern; you should probably use the built-in array splice. If you are rapidly removing things from arrays, in a tight loop and avoiding the garbage collector starts to become a concern (most games and real time simulations.) This module is more appropriate in that case.

**Comment by Cristy94** [comment]
Yes, that is exactly what I used the module for, a game running at 60FPS where objects are removed from arrays. I also use it because the arrays have usually under 10k elements, so the performance should be better than splice. 

This was not an issue, I just needed a JSPerf to test it, so I thought of posting it here maybe someone else is interested.
