### ISSUE TITLE
RangeError: Invalid array length

### ISSUE THREAD

**Issue by elieobeid7** [mreinstein/remove-array-items#8]
When I installed this library, npm said that  3 packages had high-security vulnerabilities, not sure if they're related to this library or not so I did `npm audit fix` everything got fixed and proceeded to test this library

my test

```
const removeItems = require('remove-array-items')
var arr = ['pizza', 'ice','fruit' ]
removeItems(arr, 'ice')
console.log(arr)
```
The error

```
RangeError: Invalid array length at removeItems
node_modules/remove-array-items/dist/remove-array-items.cjs.js:26   arr.length = len;
```

**Comment by mreinstein** [comment]
you need to use the index of the item you want to remove, not the item itself. This is the correct invocation:

```javascript
removeItems(arr, 1)
```

**Comment by elieobeid7** [comment]
why wouldn't I use splice() then? what's the difference?

Splice() generates garbage?

**Comment by mreinstein** [comment]
> Splice() generates garbage?

Correct. the native `splice` method returns a new array containing the removed elements. that created array will need to be garbage collected (gc) at some point. In most apps this is fine, a little extra gc isn't a big deal. It becomes a problem when you're writing code that runs in a tight loop, several thousand or millions of times a second. Think games, or animations, or simulations.
